In [10]:
import os
import pandas as pd

In [11]:
par_dir = "../data/benchmarks"

In [12]:
clr_dir = os.path.join(par_dir, "CLR")
clu_dir = os.path.join(par_dir, "CLU")

In [15]:
cca_data_path = os.path.join(clr_dir, "CCA", 'data.csv')
cca_data = pd.read_csv(cca_data_path)
cca_data.head()

,text,medra_list,doc_name
0,入院翌日に腹腔鏡下虫垂切除術を施行した。術中所見では虫垂の腫大と炎症の所見を認めたが、穿孔や...,"['虫垂炎', '発熱', '腹痛', '炎症']",117B41-42_急性虫垂炎
1,S やっぱり薬切れると痛いですね。ちょっといきむとぼこぼこ出てきます。\nO BP 125/...,"['疼痛', '肺のエアリーク', '気胸', '肋骨骨折']",12_118B35_緊張性気胸_p2
2,１１月６日 １５：００ ＃＃ Ｔ 病状説明\n＃＃ Ｓ 「本人の望むようにしてやってください...,['肺癌第４期、細胞タイプ不明'],ＮＵＭ－０００６
3,救急外来での採血結果から、高Ca血症に伴う意識障害、食思不振と判断した。\n来院時の意識レベ...,"['高カルシウム血症', '意識変容状態', '食欲減退', '意識レベルの低下', '活動...",01_118B49-50_高Ca血症
4,１１／８／２１ １０：００\n＃＃ Ｓ 痰が絡んで息がしずらい\n＃＃ Ｏ 湿性咳嗽あり 呼...,"['湿性咳嗽', '呼吸数増加', '痰貯留']",NUM-0022

In [16]:
mr_data_path = os.path.join(clr_dir, "MR", 'data.csv')
mr_data = pd.read_csv(mr_data_path)
mr_data.head()

,doc_name,text,medications
0,12_118B35_緊張性気胸_p1,S 薬が効いてきたみたいで痛みは弱くなりました。\nO BP 144/82mmHg SpO2...,"['ロキソプロフェンナトリウム水和物', 'ジクロフェナクナトリウム', 'エトドラク', ..."
1,20_118F56_高エネルギー外傷.txt,年齢 | 70 | 性別 | 男性 | 入院日 | 2025.02.19 | 退院日 | 2...,"['アムロジピンベシル酸塩', 'アトルバスタチンカルシウム水和物', 'リナグリプチン']"
2,18_118D25_高血圧性心不全_p3,S ここの食事まずくて食えないよ。味がしない。量も少ない。ラーメンとかなら食べられる気がする...,"['フロセミド', 'ダパグリフロジンプロピレングリコール水和物', 'スピロノラクトン',..."
3,05_118F61-63_術後PE_p3,S：\n・・・苦しいのはおさまりました\n\nO：\n体温37.1℃。脈拍102/分、整。血...,"['ヘパリンナトリウム', 'モンテプラーゼ']"
4,13_118B41-42_肝性脳症_p2,S おはよう。\nO 体温36.5℃。心拍数76/分、整。血圧110/64mmHg。呼吸数1...,"['肝不全用経口栄養剤', 'ラクツロース']"

In [ ]:
mr_data.head()
# replace with the current data.csv
#mr_data.to_csv(os.path.join(clr_dir, "MR", 'data.csv'), index=False)